root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "go run cmd/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test.go"]
  stop_on_error = true
  kill_on_exit = true
  pre = "powershell -Command \"Get-NetTCPConnection -LocalPort 8081 -State Listen | ForEach-Object {Stop-Process -Id $_.OwningProcess -Force}\""



[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true  # Ensure cleanup of tmp files on exit

[screen]
  clear_on_rebuild = false
